# Default values for hello-world.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: spring-projects-test

metadata:
  serviceName: spring-discovery


spec:
  minReadySeconds: 10
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  containerPort: 8081
  protocol: TCP

strategy:
  maxSurge: 1
  maxUnavailable: 1
  type: RollingUpdate

envs:
  spring.application.name: myFirstApp
  server.port: 8081

dockerImage:
  image: afsarkhan05/spring-discovery-api-service
  version: 1.0-SNAPSHOT
  imagePullPolicy: Always
  restartPolicy: Always

serviceSpec:
  name: http
  port: 8081
  protocol: TCP
  targetPort: 8081

