# Default values for hello-world.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: spring-projects

metadata:
  serviceName: spring-discovery-api


spec:
  replicas: 1
  containerPort: 8081


envs:
  spring.application.name: firstService
  server.port: 8081
  server.servlet.context-path: "/first-service"
  eureka.client.service-url.defaultZone: "http://eureka-server-service:8761/eureka"

dockerImage:
  image: afsarkhan05/spring-discovery-api-service
  version: 1.0-SNAPSHOT

serviceSpec:
  name: http
  port: 8081
  protocol: TCP
  targetPort: 8081


livenessProbe:
  failureThreshold: 10
  httpGet:
    path: /first-service/actuator/health
    port: 8081
    scheme: HTTP
  initialDelaySeconds: 180
  periodSeconds: 5
  successThreshold: 1
  timeoutSeconds: 50


# Readiness Probe Settings
readinessProbe:
  failureThreshold: 10
  httpGet:
    path: /first-service/actuator/health
    port: 8081
    scheme: HTTP
  initialDelaySeconds: 180
  periodSeconds: 5
  successThreshold: 1
  timeoutSeconds: 50
