# Default values for hello-world.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: spring-projects

metadata:
  serviceName: eureka-server


spec:
  replicas: 1
  containerPort: 8761

envs:
  SPRING_APPLICATION_NAME: eureka-server
  SERVER_PORT: 8761

dockerImage:
  image: afsarkhan05/spring-discovery-service
  version: 1.0-SNAPSHOT

serviceSpec:
  name: http
  port: 8761
  protocol: TCP
  targetPort: 8761


livenessProbe:
  failureThreshold: 3
  httpGet:
    path: /actuator/health
    port: 8761
    scheme: HTTP
  initialDelaySeconds: 10
  periodSeconds: 5
  successThreshold: 1
  timeoutSeconds: 10


# Readiness Probe Settings
readinessProbe:
  failureThreshold: 3
  httpGet:
    path: /actuator/health
    port: 8761
    scheme: HTTP
  initialDelaySeconds: 10
  periodSeconds: 5
  successThreshold: 1
  timeoutSeconds: 10
