# Default values for hello-world.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: spring-projects

metadata:
  serviceName: spring-discovery-api-service


spec:
  minReadySeconds: 10
  progressDeadlineSeconds: 100
  replicas: 1
  revisionHistoryLimit: 10
  containerPort: 8081
  protocol: TCP

strategy:
  maxSurge: 1
  maxUnavailable: 1
  type: RollingUpdate

envs:
  SPRING_APPLICATION_NAME: firstService
  SERVER_PORT: 8081

dockerImage:
  image: afsarkhan05/spring-discovery-api-service
  version: 1.0-SNAPSHOT
  imagePullPolicy: IfNotPresent
  restartPolicy: IfNotPresent

serviceSpec:
  name: http
  port: 8081
  protocol: TCP
  targetPort: 8081


livenessProbe:
  failureThreshold: 3
  httpGet:
    path: /first-service/actuator/health
    port: 8081
    scheme: HTTP
  initialDelaySeconds: 10
  periodSeconds: 5
  successThreshold: 1
  timeoutSeconds: 10


# Readiness Probe Settings
readinessProbe:
  failureThreshold: 3
  httpGet:
    path: /first-service/actuator/health
    port: 8081
    scheme: HTTP
  initialDelaySeconds: 10
  periodSeconds: 5
  successThreshold: 1
  timeoutSeconds: 10
