apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-volume
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 3Gi
  storageClassName: standard
