apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-volume
  namespace: spring-projects
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
