apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.metadata.serviceName }}-service
  namespace: {{ .Values.namespace }}
  selfLink: /api/v1/namespaces/{{ .Values.namespace }}/services/{{ .Values.metadata.serviceName }}-service
  annotations:
    {{- toYaml .Values.metadata.annotations | nindent 4 }}

spec:
  ports:
  - name: http
    port: {{ .Values.serviceSpec.port }}
    protocol: {{ .Values.serviceSpec.protocol }}
    targetPort: {{ .Values.serviceSpec.targetPort }}
  selector:
    app: {{ .Values.metadata.serviceName }}-pod
  sessionAffinity: ClientIP
  type: ClusterIP
